# Generated by Django 3.2.19 on 2023-07-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_email_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_info',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='petitcontent',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='notprice',
            new_name='url',
        ),
    ]
