# Generated by Django 3.2.19 on 2023-07-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20230707_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
